---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The buzz saw snarled and rattled in the yard  
And made dust and dropped stove-length sticks of wood,  
Sweet-scented stuff when the breeze drew across it.  
And from there those that lifted eyes could count  
Five mountain ranges one behind the other  
Under the sunset far into Vermont.  
And the saw snarled and rattled, snarled and rattled,  
As it ran light, or had to bear a load.  
And nothing happened: day was all but done.  
Call it a day, I wish they might have said  
To please the boy by giving him the half hour  
That a boy counts so much when saved from work.  
His sister stood beside him in her apron  
To tell them ‘Supper.’ At the word, the saw,  
As if to prove saws knew what supper meant,  
Leaped out at the boy’s hand, or seemed to leap—  
He must have given the hand. However it was,  
Neither refused the meeting. But the hand!  
The boy’s first outcry was a rueful laugh,  
As he swung toward them holding up the hand  